#!/usr/bin/env bash
# Iterate over open GitHub issues and ask Copilot CLI to fix each one.
# For each issue: create a branch, invoke `copilot`, push, open a PR.
#
# Requirements: gh, git, copilot CLI on PATH; run from repo root.
#
# Usage:
#   scripts/run-loop.sh [--dry-run] [--max N] [--label LABEL]

set -euo pipefail

DRY_RUN=0
MAX=0
LABEL=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    --max) MAX="$2"; shift 2 ;;
    --label) LABEL="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

for cmd in gh git; do
  command -v "$cmd" >/dev/null 2>&1 || { echo "Missing required tool: $cmd" >&2; exit 1; }
done
if ! command -v copilot >/dev/null 2>&1 && [[ "$DRY_RUN" -eq 0 ]]; then
  echo "Missing copilot CLI on PATH (install: https://github.com/github/copilot-cli)" >&2
  exit 1
fi

JQ_ARGS=(--state open --json number,title,labels --limit 100)
if [[ -n "$LABEL" ]]; then JQ_ARGS+=(--label "$LABEL"); fi

issues_json=$(gh issue list "${JQ_ARGS[@]}")
count=$(echo "$issues_json" | jq 'length')
echo "Found $count open issue(s)."

processed=0
echo "$issues_json" | jq -c '.[]' | while read -r row; do
  number=$(echo "$row" | jq -r '.number')
  title=$(echo "$row" | jq -r '.title')
  branch="copilot/issue-${number}"

  if [[ "$MAX" -gt 0 && "$processed" -ge "$MAX" ]]; then
    echo "Reached --max $MAX, stopping."
    break
  fi

  echo
  echo "=========================================="
  echo "Issue #$number: $title"
  echo "Branch: $branch"
  echo "=========================================="

  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[dry-run] would: git checkout -b $branch"
    echo "[dry-run] would: copilot -p \"...\" --allow-all-tools"
    echo "[dry-run] would: git push -u origin $branch && gh pr create ..."
    processed=$((processed + 1))
    continue
  fi

  git checkout main
  git pull --ff-only origin main || true
  git checkout -B "$branch"

  prompt=$(cat <<EOF
You are resolving GitHub issue #$number in this repository.

Title: $title

Steps:
1. Run \`gh issue view $number\` to read the full issue body and any comments.
2. Explore the codebase to understand the relevant files.
3. Make the minimal code changes needed to resolve the issue.
4. Run \`npm test\` and make sure it passes. Add or update tests when appropriate.
5. Stage and commit the changes with a message referencing the issue, e.g. "fix: <summary> (#$number)".

Do not push or open a PR — the wrapper script will handle that.
EOF
)

  copilot -p "$prompt" --allow-all-tools

  if git diff --quiet HEAD~1 HEAD 2>/dev/null; then
    echo "No commit was created by copilot for #$number — skipping push."
    processed=$((processed + 1))
    continue
  fi

  git push -u origin "$branch"
  gh pr create \
    --title "Fix #$number: $title" \
    --body "Resolves #$number. Generated by Copilot CLI loop demo." \
    --base main \
    --head "$branch" || echo "PR creation failed (maybe already exists)."

  processed=$((processed + 1))
done

echo
echo "Done. Processed $processed issue(s)."
