<#
.SYNOPSIS
  Iterate over open GitHub issues and ask Copilot CLI to fix each one.

.DESCRIPTION
  For each open issue: create a branch, invoke `copilot`, push, open a PR.
  Requirements: gh, git, copilot CLI on PATH. Run from the repo root.

.PARAMETER DryRun
  Print actions without invoking copilot or pushing.

.PARAMETER Max
  Maximum number of issues to process (0 = all).

.PARAMETER Label
  Optional label filter passed to `gh issue list`.

.EXAMPLE
  ./scripts/run-loop.ps1 -DryRun -Max 1
#>
[CmdletBinding()]
param(
  [switch]$DryRun,
  [int]$Max = 0,
  [string]$Label = ""
)

$ErrorActionPreference = "Stop"

foreach ($cmd in @("gh", "git")) {
  if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
    Write-Error "Missing required tool: $cmd"
    exit 1
  }
}
if (-not $DryRun -and -not (Get-Command "copilot" -ErrorAction SilentlyContinue)) {
  Write-Error "Missing copilot CLI on PATH (install: https://github.com/github/copilot-cli)"
  exit 1
}

$ghArgs = @("issue", "list", "--state", "open", "--json", "number,title,labels", "--limit", "100")
if ($Label) { $ghArgs += @("--label", $Label) }

$issuesJson = & gh @ghArgs | Out-String
$issues = $issuesJson | ConvertFrom-Json
Write-Host "Found $($issues.Count) open issue(s)."

$processed = 0
foreach ($issue in $issues) {
  if ($Max -gt 0 -and $processed -ge $Max) {
    Write-Host "Reached -Max $Max, stopping."
    break
  }

  $number = $issue.number
  $title  = $issue.title
  $branch = "copilot/issue-$number"

  Write-Host ""
  Write-Host "=========================================="
  Write-Host "Issue #${number}: $title"
  Write-Host "Branch: $branch"
  Write-Host "=========================================="

  if ($DryRun) {
    Write-Host "[dry-run] would: git checkout -b $branch"
    Write-Host "[dry-run] would: copilot -p `"...`" --allow-all-tools"
    Write-Host "[dry-run] would: git push -u origin $branch ; gh pr create ..."
    $processed++
    continue
  }

  git checkout main
  git pull --ff-only origin main 2>$null
  git checkout -B $branch

  $prompt = @"
You are resolving GitHub issue #$number in this repository.

Title: $title

Steps:
1. Run `gh issue view $number` to read the full issue body and any comments.
2. Explore the codebase to understand the relevant files.
3. Make the minimal code changes needed to resolve the issue.
4. Run `npm test` and make sure it passes. Add or update tests when appropriate.
5. Stage and commit the changes with a message referencing the issue, e.g. "fix: <summary> (#$number)".

Do not push or open a PR — the wrapper script will handle that.
"@

  copilot -p $prompt --allow-all-tools

  $changed = (git rev-parse HEAD) -ne (git rev-parse main)
  if (-not $changed) {
    Write-Host "No commit was created for #$number — skipping push."
    $processed++
    continue
  }

  git push -u origin $branch
  gh pr create `
    --title "Fix #${number}: $title" `
    --body "Resolves #$number. Generated by Copilot CLI loop demo." `
    --base main `
    --head $branch

  $processed++
}

Write-Host ""
Write-Host "Done. Processed $processed issue(s)."
